### ISSUE TITLE
大佬，运行后出现这个错误咋改呀

### ISSUE THREAD

**Issue by z-yyd** [hbkooo/HPVOrder#1]
Traceback (most recent call last):
  File "F:\qq\qq\FileRecv\HPVOrder-main\main.py", line 7, in <module>
    from YuemiaoPublicAccount.yuemiao import YueMiao
  File "F:\qq\qq\FileRecv\HPVOrder-main\YuemiaoPublicAccount\yuemiao.py", line 11, in <module>
    from YuemiaoPublicAccount.subscribe import subscribe_by_province, subscribe_by_region_id, subscribe
ImportError: cannot import name 'subscribe_by_province' from 'YuemiaoPublicAccount.subscribe' (F:\qq\qq\FileRecv\HPVOrder-main\YuemiaoPublicAccount\subscribe.py)
>>>

**Comment by hbkooo** [comment]
这个错误已经修改了，是我当时git上传工程的时候出了一个小错误，错误位置在下面链接处。现在的工程已经没有这个错误了。https://github.com/hbkooo/HPVOrder/blob/main/YuemiaoPublicAccount/subscribe.py#L157

**Comment by z-yyd** [comment]
[现在又变成这样了
usage: main.py [-h] [--region_id REGION_ID] [--name NAME]
               [--province PROVINCE]
               op
main.py: error: the following arguments are required: op

**Comment by hbkooo** [comment]
> [现在又变成这样了
> usage: main.py [-h] [--region_id REGION_ID] [--name NAME]
> [--province PROVINCE]
> op
> main.py: error: the following arguments are required: op

你输入的命令格式不正确吧，python main.py op --**

**Comment by z-yyd** [comment]
没有，遇到其他错误啦-------- 原始邮件 --------发件人： Hing-Hing ***@***.***>日期： 2021年7月28日周三 17:25收件人： hbkooo/HPVOrder ***@***.***>抄送： z-yyd ***@***.***>, Author ***@***.***>主    题： Re: [hbkooo/HPVOrder] 大佬，运行后出现这个错误咋改呀 (#1)

老哥，现在支持抢苗了不~~~

**Comment by z-yyd** [comment]
> 
> 
> 老哥，现在支持抢苗了不~~~

没有，遇到其他错误啦

**Comment by Hing-Hing** [comment]
> > 老哥，现在支持抢苗了不~~~Hey, Man, are you pro-gun now
> 
> 没有，遇到其他错误啦
> 
> No, I made other mistakes

老哥有没有遇到这个报错啊啊
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(3721 bytes read, 4659 more expected)', IncompleteRead(3721 bytes read, 4659 more expected))

**Comment by hbkooo** [comment]
> > > 老哥，现在支持抢苗了不~~~Hey, Man, are you pro-gun now
> > 
> > 
> > 没有，遇到其他错误啦
> > No, I made other mistakes
> 
> 老哥有没有遇到这个报错啊啊
> requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(3721 bytes read, 4659 more expected)', IncompleteRead(3721 bytes read, 4659 more expected))

可以尝试改一下requests包的版本，改成2.22.0版本的在试一下

**Comment by z-yyd** [comment]
> > > > 老哥，现在支持抢苗了不~~~Hey, Man, are you pro-gun now
> > > 
> > > 
> > > 没有，遇到其他错误啦
> > > No, I made other mistakes
> > 
> > 
> > 老哥有没有遇到这个报错啊啊
> > requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(3721 bytes read, 4659 more expected)', IncompleteRead(3721 bytes read, 4659 more expected))
> 
> 可以尝试改一下requests包的版本，改成2.22.0版本的在试一下

非常感谢！！改了之后可以运行了，order命令是检测是否有可直接预约的医院吗，如果想检测订阅量200以内的应该修改哪个参数啊

**Comment by hbkooo** [comment]
order是查询是否有哪些医院有针可以预约，发现后会发邮件通知；subscribe 这个是订阅社区医院，并没有区分订阅量是多少，根据你传入的其他参数直接订阅该参数下的所有医院。

**Comment by Hing-Hing** [comment]
> > > > 老哥，现在支持抢苗了不~~~Hey, Man, are you pro-gun now
> > > 
> > > 
> > > 没有，遇到其他错误啦
> > > No, I made other mistakes
> > 
> > 
> > 老哥有没有遇到这个报错啊啊
> > requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(3721 bytes read, 4659 more expected)', IncompleteRead(3721 bytes read, 4659 more expected))
> 
> 可以尝试改一下requests包的版本，改成2.22.0版本的在试一下

试过了，和之前一样，这个报错时有时无，有时候可以运行，有时候就会报错，脑阔疼
