### ISSUE TITLE
用户登录超时是什么情况

### ISSUE THREAD

**Issue by 814963379** [hbkooo/HPVOrder#8]
更新TK了还是用户登录超时
开始搜索抢苗...
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    flag = yuemiao.find_is_order(province=province)
  File "/www/HPVOrder-main/YuemiaoPublicAccount/yuemiao.py", line 135, in find_is_order
    linkmanId = get_linkmanId_by_name(cfg.username)
  File "/www/HPVOrder-main/YuemiaoPublicAccount/linkman.py", line 64, in get_linkmanId_by_name
    response = get_all_users()
  File "/www/HPVOrder-main/YuemiaoPublicAccount/linkman.py", line 53, in get_all_users
    response = GET(cfg.URLS['ALL_USER'], headers=cfg.REQ_HEADERS, verify=False)
  File "/www/HPVOrder-main/YuemiaoPublicAccount/util.py", line 117, in GET
    if '用户登录超时,请重新登入' in msg:
TypeError: argument of type 'NoneType' is not iterable

**Comment by chenchenT** [comment]
我的也是这个错误, 老哥你解决了吗

**Comment by chenchenT** [comment]
> 更新TK了还是用户登录超时 开始搜索抢苗... Traceback (most recent call last): File "main.py", line 59, in flag = yuemiao.find_is_order(province=province) File "/www/HPVOrder-main/YuemiaoPublicAccount/yuemiao.py", line 135, in find_is_order linkmanId = get_linkmanId_by_name(cfg.username) File "/www/HPVOrder-main/YuemiaoPublicAccount/linkman.py", line 64, in get_linkmanId_by_name response = get_all_users() File "/www/HPVOrder-main/YuemiaoPublicAccount/linkman.py", line 53, in get_all_users response = GET(cfg.URLS['ALL_USER'], headers=cfg.REQ_HEADERS, verify=False) File "/www/HPVOrder-main/YuemiaoPublicAccount/util.py", line 117, in GET if '用户登录超时,请重新登入' in msg: TypeError: argument of type 'NoneType' is not iterable


我的也是这个错误, 老哥你解决了吗

**Comment by 814963379** [comment]
没有解决，你解决了吗？

**Comment by 814963379** [comment]
> > 更新TK了还是用户登录超时 开始搜索抢苗... Traceback (most recent call last): File "main.py", line 59, in flag = yuemiao.find_is_order(province=province) File "/www/HPVOrder-main/YuemiaoPublicAccount/yuemiao.py", line 135, in find_is_order linkmanId = get_linkmanId_by_name(cfg.username) File "/www/HPVOrder-main/YuemiaoPublicAccount/linkman.py", line 64, in get_linkmanId_by_name response = get_all_users() File "/www/HPVOrder-main/YuemiaoPublicAccount/linkman.py", line 53, in get_all_users response = GET(cfg.URLS['ALL_USER'], headers=cfg.REQ_HEADERS, verify=False) File "/www/HPVOrder-main/YuemiaoPublicAccount/util.py", line 117, in GET if '用户登录超时,请重新登入' in msg: TypeError: argument of type 'NoneType' is not iterable
> 
> 我的也是这个错误, 老哥你解决了吗

你解决了吗

**Comment by github-yyh** [comment]
我也遇到这个问题了，有解决的大佬吗

**Comment by flamebobo** [comment]
![Uploading image.png…]()
同个错误，有解决的大佬吗

**Comment by fanyouzhao** [comment]
在util,py的119行，修改为            
`            if msg is not None:
                if '用户登录超时,请重新登入' in msg:
                    send_email('约苗提示错误消息：' + str(msg), subject="约苗登录超时")
                    print(msg + '\n结束抢苗')
                    exit(1)`
问题得到解决
